### PR TITLE
[WIP] Update FindGLEW to replicate upstream behaviour

### PR DESCRIPTION
**Pull request by claudiofantacci**
With this PR, I updated the FindGLEW module to replicate upstream behaviour and, in particular, to have the following features:
 - define the imported target `GLEW::glew` for the shared library GLEW;
 - if `GLEW_USE_STATIC_LIBS` is defined and set to `TRUE`, this module instad defines the imported target `GLEW::glew_s` for the static library GLEW;
 - an imported target `GLEW::GLEW` is created as a copy of either `GLEW::glew` or `GLEW::glew_s`;
 - by setting `GLEW_VERBOSE` you print out the log of the module.

### CODE REVIEW

**Comment by claudiofantacci** [comment]
Also requested to [merge upstream](https://gitlab.kitware.com/cmake/cmake/merge_requests/3094).

**Comment by claudiofantacci** [comment]
Wait before merging this, I found a little issue that I'm addressing.

**Comment by claudiofantacci** [comment]
Done 😄

**Comment by drdanz** [comment]
Let's wait and see if the upstream MR is accepted before merging this...
https://gitlab.kitware.com/cmake/cmake/merge_requests/3094

**Comment by claudiofantacci** [comment]
Merged upstream 🚀 (see https://gitlab.kitware.com/cmake/cmake/merge_requests/3094)
Will be present in CMake 3.15 🎉 

I can probably update this PR by downloading the file directly from CMake. What do you think?

**Comment by drdanz** [comment]
@claudiofantacci Awesome! I'll close this and fetch it from upstream instead. Thanks!

**Pull request closed without merging**
