### PR TITLE
Fix compatibility of FindESDCANAPI.cmake with 64 bit libraries

### PR DESCRIPTION
**Pull request by InesSorrentino**
This PR fixes the issue https://github.com/robotology/icub-main/issues/552 .

### CODE REVIEW

**Comment by traversaro** [comment]
Once merged, this needs to be propagated to `icub-main`. @pattacini we can open a PR also there if it is ok for you.

**Comment by pattacini** [comment]
> Once merged, this needs to be propagated to `icub-main`. @pattacini we can open a PR also there if it is ok for you.

Yep, please go ahead 👍

**Comment by drdanz** [comment]
LGTM, but please add a comment to the release notes (`help/release/0.9.1.rst`)

**Comment by traversaro** [comment]
> LGTM, but please add a comment to the release notes (help/release/0.9.1.rst)

@InesSorrentino : )

**Comment by traversaro** [comment]
> Yep, please go ahead +1

@InesSorrentino  : )

**Pull request merged**
