### PR TITLE
Unify default `INSTALL_DESTINATION` path

### LINKED ISSUE #305: Could the default `INSTALL_DESTINATION` path be unified?
Currently `install_basic_package_files()` chooses a platform-dependent location for the CMake config file:

https://github.com/robotology/ycm/blob/bf613de66f2eb02751c8c0c863f32ea0afa173dd/modules/InstallBasicPackageFiles.cmake#L352..L360

```cmake
  # FIXME CMake 3.7 use the same path
  # FIXME Use ARCH_INDEPENDENT to choose destination
  if(NOT DEFINED _IBPF_INSTALL_DESTINATION)
    if(WIN32 AND NOT CYGWIN)
      set(_IBPF_INSTALL_DESTINATION CMake)
    else()
      set(_IBPF_INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_Name})
    endif()
  endif()
```

This is presumably done to follow what the CMake documentation calls "Windows convention" and "Unix convention", cf. https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure.

However, CMake searches the prefixes listed in the documentation regardless of platform (cf. [source](https://gitlab.kitware.com/cmake/cmake/blob/master/Source/cmFindPackageCommand.cxx#L2103)); some subdirectories like "\<prefix\>/lib/\<arch\>/cmake/\<name\>\*/" or "\<prefix\>\/lib32/cmake/\<name\>\*/" are platform-specific, but most prefixes, and in particular "\<prefix\>/lib/cmake/\<name\>\*/" and "\<prefix\>/share/cmake/\<name\>\*/", are always searched. So making a distinction is unnecessary here as far as I can tell.

Having a platform-specific config file location causes additional complexity for [Vcpkg](https://github.com/Microsoft/vcpkg/) portfiles for packages that install with YCM's `install_basic_package_files()`. [Example](https://mp-force.ziti.uni-heidelberg.de/asc/infrastructure/vcpkg-ports/blob/master/vcpkg/ports/slowmath/portfile.cmake#L20):

```cmake
if(VCPKG_TARGET_IS_WINDOWS)
    vcpkg_fixup_cmake_targets(CONFIG_PATH "CMake" TARGET_PATH "share/<name>")
else()
    include(GNUInstallDirs) # for CMAKE_INSTALL_LIBDIR
    vcpkg_fixup_cmake_targets(CONFIG_PATH "${CMAKE_INSTALL_LIBDIR}/cmake/<name>" TARGET_PATH "share/<name>")
endif()
```

The following change to InstallBasicPackageFiles.cmake:

```diff
  if(NOT DEFINED _IBPF_INSTALL_DESTINATION)
-   if(WIN32 AND NOT CYGWIN)
-     set(_IBPF_INSTALL_DESTINATION CMake)
-   else()
      set(_IBPF_INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/${_Name})
-   endif()
  endif()
```

would simplify the portfile to

```diff
include(GNUInstallDirs) # for CMAKE_INSTALL_LIBDIR
vcpkg_fixup_cmake_targets(CONFIG_PATH "${CMAKE_INSTALL_LIBDIR}/cmake/<name>" TARGET_PATH "share/<name>")
```

Perhaps the inline FIXME comment in https://github.com/robotology/ycm/blob/master/modules/InstallBasicPackageFiles.cmake#L352 had the same intention (although I don't understand the reference to CMake 3.7).

Is there any reason why YCM has platform-specific defaults for `INSTALL_DESTINATION`, other than to follow conventions?

If this is only for conventions, perhaps it is noteworthy that Vcpkg (originally a package manager for VC++ on Windows but ported to other platforms since) has established the convention of using "\<prefix\>/share/\<name\>\*/" regardless of platform.

### PR DESCRIPTION
**Pull request by mbeutel**
Closes #305.

### CODE REVIEW

**Comment by mbeutel** [comment]
I don't think I fully understand the CI failures, but as far as I can tell they are unrelated to this specific changeset. The bootstrap test references the PR commit [88c8357969ce5b74cf84e39f68f1b682e68b8f36](https://github.com/robotology/ycm/commits/88c8357969ce5b74cf84e39f68f1b682e68b8f36), but the checkout fails with "reference is not a tree". Apparently the clone made during the bootstrap test cannot reach this commit?

Is this a known issue, and do we just ignore it here?

**Comment by drdanz** [comment]
> Is this a known issue, and do we just ignore it here?

Just ignore them... sorry about that

**Comment by drdanz** [comment]
Merged, thanks.

**Pull request merged**
