### PR TITLE
YCMBootstrap: Avoid truncating env variables list to first element in Windows

### PR DESCRIPTION
**Pull request by traversaro**
This caused the issue described in https://gitlab.kitware.com/cmake/cmake/issues/16407 .

### CODE REVIEW

**Comment by traversaro** [comment]
It think some hashes need to be updated?

**Comment by drdanz** [comment]
@traversaro Just run `tools/update_sha1sums.sh` to update the hashes...
I'm not sure why the tests pass, though...

**Comment by traversaro** [comment]
Done.

**Comment by drdanz** [comment]
Merged, thanks

**Pull request merged**
