### PR TITLE
Fix OVITO git repository URL

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/ycm/issues/103

@drdanz Do you want to fix this also for v0.1.* releases ?

### CODE REVIEW

**Comment by traversaro** [comment]
AppVeyor failure is unrelated (it is failing since https://ci.appveyor.com/project/robotology/ycm/build/0.2.1.38). I suggest to merge this as soon as possible, as at the moment all the superbuild are broken.

**Comment by traversaro** [comment]
I can't find @drdanz , abusing my newly obtained powers.

**Comment by drdanz** [comment]
Merged, thanks.
Perhaps we should release 0.2.2 very soon

**Comment by drdanz** [comment]
@traversaro i don't think that it was in 0.1, also it is no longer supported, there is the offline version available to ensure that it will build if someone really wants to do it

**Comment by liesrock** [comment]
Hi guys, we are having the same issue: YCM v0.2.0 does not compile, should we checkout master?

**Comment by traversaro** [comment]
@liesrock yes.

**Comment by traversaro** [comment]
@liesrock An alternative is to use the offline version, but for the moment I think the quickest fix is to set YCM_TAG to master or 1769c228a6aa4bcae60e86a36129891789a76558 .

**Comment by liesrock** [comment]
Ok @traversaro thanks, this is solved in this way.

**Pull request merged**
