### PR TITLE
ExternalProject sync

### PR DESCRIPTION
**Pull request by drdanz**
Update `ExternalProject` from CMake `master` and apply the patch to avoid deleting the clones.

TODO: 
- [x] Proper testing on actual superbuilds
- [ ] Test shallow clones
- [ ] (optional, but recommended) Propose the change upstream.

CC: @traversaro

### CODE REVIEW

**Comment by drdanz** [comment]
@traversaro I think we need some proper testing on actual superbuilds before merging, do you think you can help me?

**Comment by traversaro** [comment]
@drdanz can you move your branch to the `robotology` repo? This would simplify testing it via the YCM boostrap procedure and on Travis.

**Comment by traversaro** [comment]
Actually I think I can use `YCM_BOOTSTRAP_BASE_ADDRESS` to https://github.com/robotology/robotology-superbuild/blob/master/cmake/YCMBootstrap.cmake#L88 point to your fork.

**Comment by traversaro** [comment]
Test with this branch in https://github.com/robotology/robotology-superbuild/pull/144 .

**Comment by traversaro** [comment]
No, apparently the boostrap is not working correctly by changing `YCM_BOOTSTRAP_BASE_ADDRESS` ( I tried also locally). @drdanz can you move this branch to the `robotology` repo so we can test it?

**Comment by drdanz** [comment]
I'm pretty sure there was an extra comment here... Or maybe I didn't finish writing it? :thinking:

Anyway, I added a commit to the robotology-superbuild branch, it should bootstrap and download YCM from my fork now...

**Comment by traversaro** [comment]
CI tests on the superbuild are working fine both on Xenial and Bionic.

**Comment by traversaro** [comment]
@drdanz I tested it with a real superbuild and  everything seems fine. The only strange thing happens when changing a branch using `<package>_TAG` variable, during `update-all` the branch is correctly changed, but the following message is printed: 
~~~
[ 46%] Performing update step for 'iDynTree'
fatal: ambiguous argument 'testSuper': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
From https://github.com/robotology/idyntree
 * [new branch]        testSuper  -> origin/testSuper
Switched to a new branch 'testSuper'
~~~
However, despite this "strange" message everything seems to be working fine.

**Comment by drdanz** [comment]
@traversaro thanks, I'll try to figure out the message... Have you tried shallow clones or "normal" ones?

**Comment by traversaro** [comment]
> Have you tried shallow clones or "normal" ones? 

Normal ones. As far as I know, all our superbuilds are configured for doing "normal" clones.

**Comment by drdanz** [comment]
@traversaro If I understand correctly, the `fatal: ambiguous argument 'testSuper': unknown revision or path not in the working tree.` means that the `iDynTree_TAG` was set to `testSuper`, but perhaps there is also a `testSuper` file in the local commit? Anyway, I think this is something git related, I don't think we should stop this PR for this reason, what do you think? Should I proceed and merge it?

**Comment by traversaro** [comment]
Let's merge!

**Comment by traversaro** [comment]
Even because the error message was just on an obscure internal superbuild now deprecated, only due to a speicfic branch introduced to test this change itself, and apparently it was not causing any failure in the behaviour of the superbuild.

**Comment by drdanz** [comment]
I'm sorry, I squashed by mistake one commit with the release notes update...
The last commit was fixing the support for `CMAKE_CACHE_DEFAULT_ARGS`.
I suggest to use that flag instead of `CMAKE_CACHE_ARGS` more or less everywhere in the `BuildXxx.cmake` files from now on

**Pull request merged**
